### ISSUE TITLE
Wrong type comparison?

### ISSUE THREAD

**Issue by brunoseivam** [epics-base/pvAccessCPP#112]
I was trying to use the `ClientChannel::PutCallback` interface to put a value to a Channel when I was bit by this error message:

> Provided put value with wrong type

Which seems to come from here:

https://github.com/epics-base/pvAccessCPP/blob/c93f7a35f7ed4b6487fda9608a6bad7eaed79e10/src/client/clientGet.cpp#L120-L121

This tests for pointer equality. However, inside `PutCallback::putBuild` I am *not* creating a new `PVStructure` based on `build`; at that point, I already have a valid `PVStructure` that I simply want to assign to `args.root`. Hence, the pointer equality test fails.

**Comment by mdavidsaver** [comment]
oops, you caught me.  This test depends on epics-base/pvDataCPP#55 for full correctness.
