### ISSUE TITLE
pvput and CALC expressions

### ISSUE THREAD

**Issue by ttkorhonen** [epics-base/pvAccessCPP#168]
Trying to use pvput to set CALC field of a calcout record fails with a syntax that should be correct:
$ pvput timo:driveSeq.CALC "B<=A"
Old : <undefined>              B<A?VAL+1:0 INVALID DRIVER UDF 
**B< : Warning: no such field
Error: invalid bit-set length**
New : <undefined>              B<A?VAL+1:0 INVALID DRIVER UDF  

The same syntax works with caput though:

$ caput timo:driveSeq.CALC "B<=A"
Old : timo:driveSeq.CALC             B<A?VAL+1:0
New : timo:driveSeq.CALC             B<=A

A bit of a fringe case but I thought to report this nevertheless. I try to use pvtools for all my command line work.

**Comment by ralphlange** [comment]
Transferring issues is cool.

**Comment by ttkorhonen** [comment]
Thanks. This is why I was not able to transfer it, even if I tried hard...

**Comment by ralphlange** [comment]
So sorry!

**Comment by mdavidsaver** [comment]
Well, this is weird.

```
$ pvput cnt.CALC 'A>=2'
Old : 2020-09-24 07:38:41.319  A+2 
A> : Warning: no such field
New : 2020-09-24 07:38:41.319  A+2
$ pvput cnt.CALC 'A+1'
Old : 2020-09-24 07:38:50.319  A+2 
New : 2020-09-24 07:38:50.319  A+1
```

**Comment by mdavidsaver** [comment]
Ah, but of course.  It's a feature...

```
$ pvput cnt.CALC 'value=A<=2'
Old : 2020-09-24 07:50:27.319  A+2 
New : 2020-09-24 07:50:27.319  A<=2
```

**Comment by mdavidsaver** [comment]
To be explicit, this issue is an artifact of how I'm interpreting command line arguments.  Specifically, I'm doing so in two stages.  The first splits on `'='` before the remote type is known, when it isn't possible to distinguish eg. 'A' from a valid field name.  I can't think of a reason why this couldn't be changed.

**Comment by anjohnson** [comment]
CALC expressions are long strings and frequently need to be more than 40 chars. AFAIK pvget/put/monitor don't currently have an equivalent of the catools `-S` option or any other way to handle long string data. Different issue, I know...
