### ISSUE TITLE
polluting ostream flags

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-base/pvAccessCPP#177]
Some functions/methods/operators manipulate the flags of their `std::ostream` argument  for examples using `std::hex` and/or `std::setw` without saving the initial `flags()` and restoing it when done and thus polluting the state of the ostream.

Examples are:
- HexDump <<
- ResponseHandler::handleResponse
- ClientResponseHandler::handleResponse
- ServerResponseHandler::handleResponse

Also affected but in pvData:
- shared_ptr_base::show_stack

Be aware that `<<std::hex` not only affect the next value but all future values.

The solution is to save and restore the flags:
```
std::ios::fmtflags initialflags = output.flags();
output << std::hex() << ...
output.flags(initialflags);
```

**Comment by dirk-zimoch** [comment]
Correction: `setw()` resets after the next argument. But not `hex` or `setfill()`.

**Comment by anjohnson** [comment]
I'm going to assume the merge of #178 fixed this issue, please reopen if there were parts not fixed by that.
