### ISSUE TITLE
Missing LICENSE and COPYRIGHT files

### ISSUE THREAD

**Issue by ralphlange** [epics-base/pvAccessCPP#2]
*From Andrew Johnson &lt;anj_AT_aps.anl.gov&gt;:*

Module is missing LICENSE and COPYRIGHT files which are referred to in source code header comments within the module

**Comment by mdavidsaver** [comment]
Looks like this has been resolved.  I see both files now.

**Comment by msekoranja** [comment]
a comment (gdb stackdump) uses hash-number prefixes for stack frames and this accidentally referenced (and reopened) this ticket. Closing.
