### ISSUE TITLE
command line tools lack version option

### ISSUE THREAD

**Issue by gregoryraymondwhite** [epics-base/pvAccessCPP#35]
pvget, eget etc don't give an option to print version.

**Comment by dhickin** [comment]
More to the point they don't have a version to print. The only versioning is of pvAccess itself.

However as I've previously advocated I think it would be better to move pvTools out of pvAccessCPP.  I'll open an issue to discuss this separately.

**Comment by msekoranja** [comment]
@dhickin Please do not move pvTools out. This will make V4 deployment even more complex. Imagine not getting caget/caput with EPICS base.

**Comment by dhickin** [comment]
OK, it was just a suggestion. I opened the issue already, but if there's not agreement it can just be closed.

**Comment by gregoryraymondwhite** [comment]
The command line tools surely do have a version to print. You might argue that they have too many to make implementation easy, but you can't really argue that they have none. For instance, answering questions like which syntax of pvRequest is understood, which normative types does it understand.

**Comment by mdavidsaver** [comment]
> ... The only versioning is of pvAccess itself.

This seems like an easy answer to me.  Include pvaVersion.h and print EPICS_PVA_*_VERSION.

**Comment by gregoryraymondwhite** [comment]
Yes, that would be fine.
