### ISSUE TITLE
Move pvTools out of pvAccessCPP

### ISSUE THREAD

**Issue by dhickin** [epics-base/pvAccessCPP#38]
I think it would be better to move pvTools to a separate repository.

I’m not sure they really belong in pvAccessCPP. I guess the main reason for keeping them there is that they are fairly small and previously there wasn't a strong enough case for the extra overhead in having another repo.

However now moving them out would enable pvTools to use normativeTypes and pvaClient in future, whilst maintaining  the current extremely clean and logical dependencies.

The tools currently all reside in their own source directory so it should be fairly straight-forward.

**Comment by msekoranja** [comment]
I would only consider moving eget out (since it has knowledge of normativeTypes).

**Comment by mdavidsaver** [comment]
I'll second Matej.  Please don't move pvget/put/info.

**Comment by anjohnson** [comment]
I also disagree with moving the pvtools.

Does eget have its own implementations of the normative types? pvAccess doesn't require the normativeTypes module to build IIRC.

**Comment by msekoranja** [comment]
eget does does extracting data (according to specification) on it's own. eget existed long before normativeTypesCPP. 
normativeTypeCPP are "just" helpers classes around pvData structures.

**Comment by dhickin** [comment]
OK, let's keep them where they are.

Only eget uses normative types (with as Matej says their own implementation). The idea was that eget would be able to use normativeTypesCPP and all the tools could use pvaClientCPP. If we were going to make such a move then now would have been a sensible time if we were considering a versioning scheme.

I do see the advantage in packaging the tools without requiring higher-level libraries, so I'm happy to close this.
