### ISSUE TITLE
Monitors do not work when client requests provider ca

### ISSUE THREAD

**Issue by mrkraimer** [epics-base/pvAccessCPP#50]
When a client tries to create a monitor that uses provider ca, a failure occurs when monitor is started.

**Comment by mrkraimer** [comment]
Bad title. 
Should have said
"Monitors do not work when client requests provider ca"

**Comment by arkilic** [comment]
Nice to have you back @mrkraimer 👍

**Comment by mrkraimer** [comment]
I have added more debug output to
https://github.com/mrkraimer/pvaClientCPP
and
https://github.com/mrkraimer/exampleCPP

To demonstrate the monitor problem build against the above and then

1) Start the example database as part on a V3 IOC
mrk> pwd
/home/epicsv4/master/exampleCPP/database/iocBoot/exampleDatabase
mrk> ../../bin/linux-x86_64/exampleDatabase st.cmd

2) Then run monitorForever.
The following works just fine
/home/epicsv4/master/exampleCPP/exampleClient
mrk> bin/linux-x86_64/monitorForever pva DBRdouble00 false.

But the following crashes
mrk> bin/linux-x86_64/monitorForever ca DBRdouble00 false
provider "ca" pvaSrv false caSrv true channelName DBRdouble00 debug false
_____monitorForever starting_______
Segmentation fault (core dumped)

To see debug info run
mrk> valgrind bin/linux-x86_64/monitorForever ca DBRdouble00 true

**Comment by mrkraimer** [comment]
I have spent some more time looking at the problem.
It was in pvaClientCPP NOT in pvAccessCPP.

The fix is

diff --git a/src/pvaClientMonitor.cpp b/src/pvaClientMonitor.cpp
index ebfb361..6bdd970 100644
--- a/src/pvaClientMonitor.cpp
+++ b/src/pvaClientMonitor.cpp
@@ -240,7 +240,7 @@ Status PvaClientMonitor::waitConnect()
 {
     if(PvaClient::getDebug()) cout << "PvaClientMonitor::waitConnect\n";
     if(connectState==connected) {
-         if(connectStatus.isOK()) connectState = connectIdle;
+         if(!connectStatus.isOK()) connectState = connectIdle;
          return connectStatus;
     }

I am closing this issue.

Sorry Matej!!!!
