### ISSUE TITLE
ClientFactory::stop has memory leaks

### ISSUE THREAD

**Issue by mrkraimer** [epics-base/pvAccessCPP#51]
When ClientFactory::stop is called memory leaks often occur.

**Comment by mdavidsaver** [comment]
I think this should now be resolved.  The PVA client provider factory is now automatically removed during epicsExit().  Also, now only a weak_ptr to the shared instance is kept, limiting the scope for ref. leaks.

**Comment by mrkraimer** [comment]
This will be fixed  in release 6.0.
Until then it is fixed on branch master.

**Comment by mdavidsaver** [comment]
Released in module version 6.0.0, bundle version 7.0.1
