### ISSUE TITLE
ServerContext shows memory leaks when destroy is called.

### ISSUE THREAD

**Issue by mrkraimer** [epics-base/pvAccessCPP#52]
When the destroy method of ServerContext is called valgrind shows memory leaks.

**Comment by mdavidsaver** [comment]
Yup, the worker thread leaks a reference.  Of course the worker thread is also a no-op after startup (sits in Event::wait() and does nothing) so it isn't necessary.  So this is resolved by ce25f0b17540cab011deb4b300a24f5b9c5198c2 on https://github.com/mdavidsaver/pvAccessCPP

**Comment by mdavidsaver** [comment]
I think this has been resolved by my recent changes.  This includes, but is not limited to ce25f0b17540cab011deb4b300a24f5b9c5198c2 and 6fcfd60bd50092e2263dd00c1cb1cbce68c0f7fd

**Comment by mdavidsaver** [comment]
Released in module version 6.0.0, bundle version 7.0.1
