### ISSUE TITLE
caProvider requires channel connect before createGet, etc.

### ISSUE THREAD

**Issue by mrkraimer** [epics-base/pvAccessCPP#64]
Proider pva allows createChannelGet, channelPut, etc before a channel connects.
Provider ca should provide the same functionality.

**Comment by mrkraimer** [comment]
This will be fixed  in release 6.0.
Until then it is fixed on branch master.

**Comment by mdavidsaver** [comment]
Released in module version 6.0.0, bundle version 7.0.1
