### ISSUE TITLE
unknown provider name 'pva'

### ISSUE THREAD

**Issue by mdavidsaver** [epics-base/pvAccessCPP#87]
Apparently during static linking an anonymous namespace can optimized out even if it has side-effects (global w/ ctor).  At least by g++

At issue is pvaloaderinstance in clientFactory.cpp

https://github.com/epics-base/pvAccessCPP/blob/6fd9212230fedd5449149803793cdb761bb758f2/src/pva/clientFactory.cpp#L46-L53

**Comment by mdavidsaver** [comment]
Ok, this is a stupid one on my part.  During static linking, ld entirely ignores clientFactory.o as none of it's symbols are used by pvlist and friends.  Global ctors are retained if _any_ symbol from a file is used.  Apparently this is a long standing "feature" of binutils (http://www.sourceware.org/ml/binutils/2003-02/msg00155.html).

**Comment by mdavidsaver** [comment]
Should be fixed with abce3faa8675c92b9e8b00a26ad17b81aed84557

**Comment by mdavidsaver** [comment]
Well, I can't claim that this was new to me either.  I'd just forgotten.

**Comment by hhslepicka** [comment]
Thank you for the fix @mdavidsaver . I can confirm that the fix work since I tested it here at SLAC.

**Comment by mdavidsaver** [comment]
Thanks Hugo.

**Comment by mdavidsaver** [comment]
Released with Base 7.0.2
